
const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE :'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    //-------------------admin-----------------

//gender
    ADD_GENDER_START:"ADD_GENDER_START",
    ADD_GENDER_SUCCESS:"ADD_GENDER_SUCCESS",
    ADD_GENDER_FAiDED:"ADD_GENDER_FAiDED",
    //position
    ADD_POSITION_START:"ADD_POSITION_START",
    ADD_POSITION_SUCCESS:"ADD_POSITION_SUCCESS",
    ADD_POSITION_FAiDED:"ADD_POSITION_FAiDED",
    //ROLE
    ADD_ROLE_START:"ADD_ROLE_START",
    ADD_ROLE_SUCCESS:"ADD_ROLE_SUCCESS",
    ADD_ROLE_FAiDED:"ADD_ROLE_FAiDED",
   //C
   CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
   CREATE_USER_FAiDED:"CREATE_USER_FAiDED",
   //R
   FETCH_ALL_USER_SUCCESS:"FETCH_ALL_USER_SUCCESS",
   FETCH_ALL_USER_FAIL:"FETCH_ALL_USER_FAIL",
   //D
   DELETE_USER_SUCCESS:"DELETE_USER_SUCCESS",
   DELETE_USER_FAIDED:"DELETE_USER_FAIDED",
   //U
   UPDATE_USER_SUCCESS:" UPDATE_USER_SUCCESS",
   UPDATE_USER_FAIDED:"UPDATE_USER_FAIDED",
   //top doctor
   FETCH_TOP_DOCTOR_SUCCESS:"FETCH_TOP_DOCTOR_SUCCESS",
   FETCH_TOP_DOCTOR_FAIDED:"FETCH_TOP_DOCTOR_FAIDED",
   //all doctor
   FETCH_ALL_DOCTOR_SUCCESS:"FETCH_ALL_DOCTOR_SUCCESS",
   //Detail 
   ALERT_RES_DETAIL_DOCTOR:" ALERT_RES_DETAIL_DOCTOR",
   GET_DETAIL_DOCTOR_BY_ID:'GET_DETAIL_DOCTOR_BY_ID',
  
   
})

export default actionTypes;